config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views
from portfolio import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/',include('pybo.urls')),
    path('common/',include('common.urls')),
    path('', views.index, name='index'),    # '/' 에 해당하는 path
    path('portfolio/', include('portfolio.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path
from . import views

from django.conf.urls.static import static
from django.conf import settings

app_name='portfolio'

urlpatterns = [
    path('', views.index, name="index"),
    path('guestbook/create/', views.guestbook_create, name='guestbook_create'),
#    path('guestbook/modify/', views.guestbook_modify, name='guestbook_modify'),
#    path('guestbook/delete/', views.guestbook_delete, name='guestbook_delete'),
    path('Who_is_Mori?/', views.who, name="who"),
    path('Where_is_Mori?/', views.where, name="where"),
    path('What_Mori_can_do/', views.what, name="what"),
    path('FileUpload/', views.FileUpload, name='fileupload'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pybo/urls.py
from django.urls import path

from .views import base_views, question_views, answer_views

app_name = 'pybo'

urlpatterns = [
    # base_views.py
    path('', base_views.index, name='index'),
    path('<int:question_id>/', base_views.detail, name='detail'),

    # question_views.py
    path('question/create/', question_views.question_create, name='question_create'),
#   path('question/modify/<int:question_id>', question_views.question_modify, name='question_modify')

    # answer_views.py
    path('answer/create/<int:question_id>', answer_views.answer_create, name='answer_create'),
]

portfolio/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
    name = models.CharField(max_length=10)
    image = models.ImageField(upload_to='userimage/', blank=True)
    age = models.IntegerField()
    introduce = models.CharField(max_length=200)
    email = models.EmailField()
    def __str__(self):
        return self.name
class Guestbook(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField(null=True)
    def __str__(self):
        return self.content

class FileUpload(models.Model):
    title = models.TextField(max_length=50)
    imgfile = models.ImageField(null=True, upload_to="", blank=True)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    create_date = models.DateTimeField(null=True)

    def __str__(self):
        return self.title

portfolio/forms.py
from django import forms
from .models import UserProfile, Guestbook, FileUpload

class UserGuestBookForm(forms.ModelForm):
    class Meta:
        model = Guestbook
        fields = ['content']
        labels = {
            'content': '내용',
        }

class FileUploadForm(forms.ModelForm):
    class Meta:
        model = FileUpload
        fields =['title', 'imgfile', 'content']
        label = {
            'title': '제목',
            'imgfile': '사진',
            'content': '내용',
        }

portfolio/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseNotAllowed
from django.utils import timezone
from django.contrib import messages
from django.core.paginator import Paginator

from .models import UserProfile, Guestbook, FileUpload
from .forms import UserGuestBookForm, FileUploadForm

def index(request):
    guestbook = Guestbook.objects.order_by('-create_date')
    context = {'guestbook': guestbook}
    return render(request, 'portfolio/main.html', context)

def guestbook_create(request):
    guestbook = Guestbook.objects.order_by('-create_date')
    if request.method == "POST":
        form = UserGuestBookForm(request.POST)
        if form.is_valid():
            guest = form.save(commit=False)
            guest.create_date = timezone.now()
            guest.author = request.user
            guest.save()
            return redirect('portfolio:index')
    else:
        form = UserGuestBookForm()
    context = {'guestbook': guestbook, 'form': form}
    return render(request, 'portfolio/main.html', context)

"""
def guestbook_modify(request, guestbook_id):
    guestbook = get_object_or_404(Guestbook, pk=guestbook_id)
    if request.user != guestbook.author:
        messages.error(request, '수정권한이 없습니다!')
        return redirect('portfolio:index')
    if request.method == "POST":
        form = UserGuestBookForm(request.POST, instance=guestbook)
        if form.is_valid():
            guestbook = form.save(commit=False)
            guestbook.create_date = timezone.now()
            guestbook.save()
            return redirect('portfolio:index')
    else:
        form = UserGuestBookForm(instance=guestbook)
    context = {'guestbook': guestbook, 'form': form}
    return render(request, 'portfolio/main.html', context)
"""

"""
def guestbook_delete(request):
    guestbook = Guestbook.objects.get()
    if not request.user.is_superuser:
        messages.error(request, '권한이 없습니다.')
    else:
        guestbook.delete()
        return redirect('portfolio:index')
    return redirect('portfolio:index')
"""

def who(request):
    return render(request, 'portfolio/profile.html')

def where(request):
    return render(request, 'portfolio/hometown.html')

def File_Upload(request):
    if request.method == 'POST':
        form = FileUploadForm(request.POST)
        if form.is_valid():
            fileupload = form.save(commit=True)
            fileupload.create_date = timezone.now()
            fileupload.author = request.user
            fileupload.save()
            return redirect('portfolio:what')
    else:
        form = FileUploadForm()
    context = {'form': form}
    return render(request, 'portfolio/fileupload.html', context)

def what(request):
    page = request.GET.get('page','1')
    file_list = FileUpload.objects.all()
    paginator = Paginator(file_list, 10)
    page_obj = paginator.get_page(page)
    context = {'file_list': page_obj}
    return render(request, 'portfolio/ability.html', context)

templates/portfolio/ability.html
{% extends 'base.html' %}
{% load portfolio_filter %}
{% block content %}

<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="text-center table-dark">
            <th>번호</th>
            <th style="width:50%">제목</th>
            <th>글쓴이</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if file_list %}
        {% for file in file_list %}
        <tr class="text-center">
            <td>
                <!-- 번호 = 전체 건수 - 시작인덱스 - 현재인덱스 + 1 -->
                {{ file_list.paginator.count|sub:file_list.start_index|sub:forloop.counter0|add:1 }}
            </td>
            <td class="text-start">
                <a href="{% url 'portfolio:what' question.id %}">{{ file.subject }}</a>
            </td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="4">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징처리 시작 -->
    <u1 class="pagination justify-content-center">
        <!-- 이전 페이지 -->
        {% if file_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ file_list.previous_page_number }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in file_list.paginator.page_range %}
        {% if page_number >= file_list.number|add:-5 and page_number <= file_list.number|add:5 %}
        {% if page_number == file_list.number %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
        </li>
        {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if question_list.has_next %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </u1>
    <!-- 페이징처리 끝 -->
    <a href="{% url 'portfolio:fileupload' %}" class="btn btn-outline btn-warning">질문 등록하기</a>
</div>

{% endblock %}

templates/portfolio/fileupload.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post" action="{% url 'portfolio:fileipload' %}" enctype="multipart/form-data">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="title" class="form-label">제목</label>
            <input type="text" class="form-control" name="title" id="title"
                   value="{{ form.title.value|default_if_none:'' }}">
        </div>

        <div class="mb-3">
            <label for="content" class="form-label">내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-warning">저장하기</button>
    </form>
</div>
{% endblock %}

templates/portfolio/hometown.html
{% extends 'base.html' %}
{% block content %}



{% endblock %}

templates/portfolio/main.html
{% extends 'base.html' %}
{% block content %}

<!-- message 표시
{% if messages %}
<div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
</div>
{% endif %}
-->

<div>
    <h3 class="text-center border-bottom my-4"><b>Stay Home</b></h3>
    <div class="text-center">
        <img src="/static/img/clap_mori.jpg" class="img-thumbnail" width="300" height="300">
    </div>
    <div class="my-1"></div>
</div>

<div class="container my-5 text-center">
    <div class="row">
        <div class="col">
            <div class="p-3 border bg-light">
                <a href="{% url 'portfolio:who' %}" class="btn btn-outline-warning" role="button" aria-pressed="true">Who is Mori</a>
            </div>
        </div>
        <div class="col">
            <div class="p-3 border bg-light">
                <a href="{% url 'portfolio:where' %}" class="btn btn-outline-warning" role="button" aria-pressed="true">Where is Mori?</a>
            </div>
        </div>
        <div class="col">
            <div class="p-3 border bg-light">
                <a href="{% url 'portfolio:what' %}" class="btn btn-outline-warning" role="button" aria-pressed="true">What Mori can do?</a>
            </div>
        </div>
    </div>
</div>

<!-- 답변 -->
{% for book in guestbook %}
<div class="container">
        {% csrf_token %}
        <div class="card my-3">
            <div class="card-body">
                <div class="card_text" style="white-space: pre-line;">{{ book.content }}</div>
                <div class="d-flex justify-content-end">
                    <div class="badge bg-light text-dark p-2 text-start">
                        {% if request.user.is_superuser %}
                        <div class="mb-2">{{ book.author.username }}</div>
                        {% endif %}
                        <div>{{ book.create_date }}</div>

                        {% comment %}
                        <!-- 수정버튼
                        <div class="my-3">
                            {% if request.user == book.author %}
                            <a href="{% url 'portfolio:guestbook_modify' %}"
                               class="btn btn-sm btn-outline-warning">수정</a>
                            {% endif %}
                        </div>
                        -->
                        {% endcomment %}
                    </div>
                </div>
                {% if request.user.is_superuser %}
                <a href="{% url 'portfolio:index' %}" class="btn btn-sm btn-outline-warning">삭제</a>
                {% endif %}
            </div>
        </div>
    </form>
</div>
{% endfor %}

<div class="container">
    <form action="{% url 'portfolio:guestbook_create' %}" method="post">
        {% csrf_token %}
        <label for="content" class="form-label">방명록</label>
        <textarea {% if not user.is_authenticated %}disabled{% endif %}
                class="form-control" name="content" id="content" rows="5"></textarea>
        <button type="submit" class="btn btn-outline-warning my-1">등록</button>
    </form>
</div>

{% endblock %}

templates/portfolio/profile.html
{% extends 'base.html' %}
{% block content %}

<div class="px-5 py-2 bg-warning bg-opacity-25 text-secondary">
    <h3 class="my-4 border-bottom border-danger"><b>Profile</b></h3>
    <div class="row">
        <img src="/static/img/smile_mori.jpg" class="col-2 img-thumbnail mb-3">
        <div class="col offset-md container">
            <h4><b>NAME : PlppIle</b></h4>
            <h5>
                <b>
                    AGE : ??</br>
                    SEX : FM</br>
                    EMAIL : whitney2319@naver.com</br>
                    GITHUB ADD :
                    <a href="https://github.com/PlppIle">PlppIle</a></br>
                    INTRODUCE : 세상에서 가장 귀여운 모리를 모두에게 보여드리겠습니다.</br>
                    COMPUTER LANGUAGE : C, PYTHON
                </b>
            </h5>
        </div>
    </div>
{% endblock %}